#!/bin/bash

if [ ! -f /usr/local/bank/bank-jar-with-dependencies.jar ]
then 
	echo "Library not found, project may have not been compiled yet"
	exit 1
fi
COLUMNS=$(tput cols)
java  --add-modules java.xml.bind --add-opens java.base/java.lang=ALL-UNNAMED -cp /usr/local/bank/bank-jar-with-dependencies.jar com.sleroux.bank.Bank $@ columns:$COLUMNS
