#!/bin/bash
set -e

function fail(){
	echo "*** Installation failed ! ***"
	exit 1
}

export VERSION=`java -jar target/bank-jar-with-dependencies.jar columns:0 version`

export INSTALL_PATH=/usr/local/bank-$VERSION
export LINK=/usr/local/bin/bank

unzip -q -c target/bank-jar-with-dependencies.jar com/sleroux/bank/presentation/header.ascii
echo ""
#echo "previous version : $(bank version)"
echo "new version      : $VERSION"
echo "Install path     : $INSTALL_PATH"
echo "Linked to        : $LINK"
echo ""
echo "sudo password :"

sudo mkdir -p $INSTALL_PATH
sudo rm -fv /usr/local/bank 
sudo ln -sv $INSTALL_PATH /usr/local/bank 
sudo cp -Rfv ./target/bank-jar-with-dependencies.jar $INSTALL_PATH/


rm -f ${LINK} 1>/dev/null


(
	cp -Rfv ./bank ${LINK}
	chmod +x ${LINK} 
) 1>/dev/null

