package com.sleroux.bank.domain;

public enum AlertType {
	UNDEFINED, CATEGO_CONFLICT,
	DEBIT_BURNED, DEBIT_NOT_BUDGETED, DEBIT_OVER_ESTIMATE,
	CREDIT_BURNED, CREDIT_NOT_BUDGETED, CREDIT_OVER_ESTIMATE, NO_ALERT

}
